name: Release on File Change

on:
  push:
    branches:
      - main
  workflow_dispatch:
  repository_dispatch:
    types: [file-changed]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Check for file changes
      id: file_changes
      run: |
        if git diff-tree --name-only HEAD^ HEAD | grep -q 'openai.txt'; then
          echo "::set-output name=changed::true"
        else
          echo "::set-output name=changed::false"
        fi

    - name: Create release
      id: create_release
      if: ${{ needs.file_changes.outputs.changed == 'true' }}
      run: |
        echo "Creating release..."
        tag_name=$(date +'%Y%m%d%H%M%S')
        echo "::set-output name=tag_name::$tag_name"
        # Add your release creation logic here

        echo "Uploading openai.txt..."
        upload_url=$(curl --request POST \
          --url "https://uploads.github.com/repos/${{ github.repository }}/releases/${{ needs.create_release.outputs.id }}/assets?name=openai.txt" \
          --header "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          --header "Content-Type: text/plain" \
          --data-binary "@openai.txt" \
          --silent \
          --location | jq -r '.url')

        echo "::set-output name=upload_url::$upload_url"

    - name: Publish release
      id: publish_release
      if: ${{ needs.create_release.outputs.tag_name != '' }}
      run: |
        echo "Publishing release..."
        # Add your release publishing logic here
